/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package simp;

import common.VerticalFlowLayout;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author vsd
 */
public class DecoGasPanel extends javax.swing.JPanel {
    private main aThis;

    /**
     * Creates new form PlanPanel
     */
    public DecoGasPanel() {
        initComponents();
        jpAtoms.setLayout(new VerticalFlowLayout(0, VerticalFlowLayout.LEFT));
        addAtom("100",false);
        addAtom("50",true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jpAtoms = new javax.swing.JPanel();

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jpAtoms.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(jpAtoms);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 366, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addAtom(null,true);

    }//GEN-LAST:event_jButton1ActionPerformed


    private void removeAtom(ActionEvent ae) {
        DecoGasAtom atom=(DecoGasAtom)((JButton)ae.getSource()).getParent();
        atom.clearDCD();
        jpAtoms.remove(((JButton)ae.getSource()).getParent());
        jpAtoms.revalidate();
        jpAtoms.repaint();
        aThis.updateDeco();
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel jpAtoms;
    // End of variables declaration//GEN-END:variables

    public void addAtom(String gas,Boolean active) {
        DecoGasAtom atom=new DecoGasAtom(gas,active);
        atom.jbRemove.addActionListener(new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent ae) {
               removeAtom(ae);
            }
        });
        jpAtoms.add(atom);
        jpAtoms.revalidate();
        jpAtoms.repaint();
    }

    void setMain(main aThis) {
        this.aThis=aThis;
    }
}
